name: Go Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Go 环境
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: 编译 Linux AMD64
      run: |
        GOOS=linux GOARCH=amd64 go build -o argo-linux-amd64 .

    - name: 编译 Linux ARM64
      run: |
        GOOS=linux GOARCH=arm64 go build -o argo-linux-arm64 .

    - name: 创建 Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          argo-linux-amd64
          argo-linux-arm64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
