name: Go Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        # 创建输出目录
        mkdir -p build
        
        # 设置输出文件名
        OUTPUT_FILE="build/argo-${{ matrix.goos }}-${{ matrix.goarch }}"
        
        # 编译
        go build -v -o $OUTPUT_FILE .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: argo-${{ matrix.goos }}-${{ matrix.goarch }}
        path: build/argo-${{ matrix.goos }}-${{ matrix.goarch }}
