name: Go Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 设置 Go 环境
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: 编译
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        mkdir -p dist
        go build -v -o dist/argo-${{ matrix.goos }}-${{ matrix.goarch }} .

    - name: 上传构建产物
      uses: actions/upload-artifact@v1
      with:
        name: argo-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/argo-${{ matrix.goos }}-${{ matrix.goarch }}
